apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"release":"prometheus"},"name":"webhook-app","namespace":"default"},"spec":{"endpoints":[{"port":"web"}],"selector":{"matchLabels":{"app":"webhook-app"}}}}
  creationTimestamp: "2022-03-05T20:50:57Z"
  generation: 1
  labels:
    release: prometheus
  name: webhook-app
  namespace: default
  resourceVersion: "6616477"
  uid: 13af720d-7f8e-42c4-839e-1f7fdb976f0d
spec:
  endpoints:
  - port: web
  selector:
    matchLabels:
      app: webhook-app
