apiVersion: v1
kind: Namespace
metadata:
  name: rocketchat
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmongo
  namespace: rocketchat
  labels:
    app: rocketmongo
spec:
  selector:
    app: rocketmongo
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmongo
  namespace: rocketchat
spec:
  serviceName: rocketmongo
  replicas: 2
  selector:
    matchLabels:
      app: rocketmongo
  template:
    metadata:
      labels:
        app: rocketmongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: rocketmongo
          image: mongo:4.0
          command:
          - mongod
          - "--smallfiles"
          - "--oplogSize"
          - "128"
          - "--replSet"
          - "rs0"
          - "--storageEngine=mmapv1"
          - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-server
  namespace: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-server
  template:
    metadata:
      labels:
        app: rocketchat-server
    spec:
      containers:
        - name: rocketchat-server
          image: rocketchat/rocket.chat:latest
          command: ["/bin/bash"]
          args: ["-c",
              "for i in `seq 1 30`; do
                node main.js &&
                s=$$? && break || s=$$?;
                echo \"Tried $$i times. Waiting 5 secs...\";
                sleep 5;
              done; (exit $$s)"]          
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://rocketmongo-0.rocketmongo:27017,rocketmongo-1.rocketmongo:27017/rocketchat
            - name: MONGO_OPLOG_URL
              value: mongodb://rocketmongo-0.rocketmongo:27017,rocketmongo-1.rocketmongo:27017/local?replSet=rs0
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: rocketchat-server
  namespace: rocketchat
spec:
  selector:
    app: rocketchat-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---

